--------------------------------------------------------
--  File created - Selasa-Mei-09-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MST_KOTA
--------------------------------------------------------

  CREATE TABLE "MST_KOTA" 
   (	"KODE_KOTA" VARCHAR2(20 CHAR), 
	"KODE_PROVINSI" VARCHAR2(20 CHAR), 
	"NAMA_KOTA" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into MST_KOTA
Insert into MST_KOTA (KODE_KOTA,KODE_PROVINSI,NAMA_KOTA) values ('JKTPUSAT','DKI JAKARTA','JAKARTA PUSAT');
Insert into MST_KOTA (KODE_KOTA,KODE_PROVINSI,NAMA_KOTA) values ('JKTTIMUR','DKI JAKARTA','JAKARTA TIMUR');
Insert into MST_KOTA (KODE_KOTA,KODE_PROVINSI,NAMA_KOTA) values ('JKTSELATAN','DKI JAKARTA','JAKARTA BARAT');
Insert into MST_KOTA (KODE_KOTA,KODE_PROVINSI,NAMA_KOTA) values ('JKTBARAT','DKI JAKARTA','JAKARTA BARAT');
Insert into MST_KOTA (KODE_KOTA,KODE_PROVINSI,NAMA_KOTA) values ('JKTUTARA','DKI JAKARTA','JAKARTA UTARA');
Insert into MST_KOTA (KODE_KOTA,KODE_PROVINSI,NAMA_KOTA) values ('BKSI','BKS','BEKASI KOTA');
--------------------------------------------------------
--  DDL for Index MST_KOTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MST_KOTA_PK" ON "MST_KOTA" ("KODE_KOTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MST_KOTA
--------------------------------------------------------

  ALTER TABLE "MST_KOTA" ADD CONSTRAINT "MST_KOTA_PK" PRIMARY KEY ("KODE_KOTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MST_KOTA" MODIFY ("KODE_KOTA" NOT NULL ENABLE);
