--------------------------------------------------------
--  File created - Selasa-Mei-09-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MST_KARYAWAN
--------------------------------------------------------

  CREATE TABLE "MST_KARYAWAN" 
   (	"KODE_KARYAWAN" VARCHAR2(20 CHAR), 
	"NAMA_KARYAWAN" VARCHAR2(100 CHAR), 
	"PASSWORD" VARCHAR2(100 CHAR), 
	"USERNAME" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into MST_KARYAWAN
Insert into MST_KARYAWAN (KODE_KARYAWAN,NAMA_KARYAWAN,PASSWORD,USERNAME) values ('ADM','AGUS','SKD','AGS');
Insert into MST_KARYAWAN (KODE_KARYAWAN,NAMA_KARYAWAN,PASSWORD,USERNAME) values ('asad','dsda11q','aeraerfafafs','tes1');
--------------------------------------------------------
--  DDL for Index MST_KARYAWAN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MST_KARYAWAN_PK" ON "MST_KARYAWAN" ("KODE_KARYAWAN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MST_KARYAWAN
--------------------------------------------------------

  ALTER TABLE "MST_KARYAWAN" ADD CONSTRAINT "MST_KARYAWAN_PK" PRIMARY KEY ("KODE_KARYAWAN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MST_KARYAWAN" MODIFY ("KODE_KARYAWAN" NOT NULL ENABLE);
