--------------------------------------------------------
--  File created - Selasa-Mei-09-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MST_PROVINSI
--------------------------------------------------------

  CREATE TABLE "MST_PROVINSI" 
   (	"KODE_PROVINSI" VARCHAR2(20 CHAR), 
	"NAMA_PROVINSI" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into MST_PROVINSI
Insert into MST_PROVINSI (KODE_PROVINSI,NAMA_PROVINSI) values ('DKI JAKARTA','IBU KOTA JAKARTA');
Insert into MST_PROVINSI (KODE_PROVINSI,NAMA_PROVINSI) values ('BKS','BEKASI');
--------------------------------------------------------
--  DDL for Index MST_PROVINSI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MST_PROVINSI_PK" ON "MST_PROVINSI" ("KODE_PROVINSI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MST_PROVINSI
--------------------------------------------------------

  ALTER TABLE "MST_PROVINSI" ADD CONSTRAINT "MST_PROVINSI_PK" PRIMARY KEY ("KODE_PROVINSI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MST_PROVINSI" MODIFY ("KODE_PROVINSI" NOT NULL ENABLE);
